### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by Zaelyth** [otorexia/phaser3-webpack#4]
Can you provide some simple examples/docs to show off the workflow of your setup ?
Or simply explain how to achieve straight forward tasks such as adding tilemaps, sounds, and sprites. (btw, awesome setup, will try it right now)

**Comment by otorexia** [comment]
Hey, thanks for checking it out. you can find most of the basic instruction on readme and also in each file as comments. I'll create a sample game if I have some free time.
